### ISSUE TITLE
Cannot parse capsule error

### ISSUE THREAD

**Issue by BolunDai0216** [ros/urdfdom#192]
Hi,

I have a URDF with many capsule tags, and everytime I load the URDF I get a series of errors like this one

```txt
Error:   Could not parse visual element for Link [link6_primitive]
         at line 453 in /home/conda/feedstock_root/build_artifacts/urdfdom_1704626483899/work/urdf_parser/src/link.cpp
Error:   Unknown geometry type 'capsule'
         at line 262 in /home/conda/feedstock_root/build_artifacts/urdfdom_1704626483899/work/urdf_parser/src/link.cpp
```

Does anyone know what might be the issue here?

Thanks in advance!

**Comment by clalancette** [comment]
That's because `capsule` isn't a supported geometry type in URDF.  It means that your URDF file contains a `capsule` XML element somewhere in it, and URDF doesn't support that.

Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
